DROP DATABASE cybercomm;

CREATE DATABASE cybercomm;

use cybercomm;

source DBcreator.sql;

LOAD DATA LOCAL INFILE 'CC\ mysql/UA/UA.txt' 
	INTO TABLE UA FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n' 
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'CC\ mysql/UA/UA_US.txt' 
	INTO TABLE UA_US FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n' 
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'CC\ mysql/RR/RR.txt' 
	INTO TABLE RR FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n' 
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'CC\ mysql/RR/RR_US.txt' 
	INTO TABLE RR_US FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n' 
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'CC\ mysql/CC/CC.txt' 
	INTO TABLE CC FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n' 
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'CC\ mysql/CC/CC_US.txt' 
	INTO TABLE CC_US FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' 
	LINES TERMINATED BY '\n' 
	IGNORE 1 LINES;

source CCsum.sql;
source RRsum.sql;
source UAsum.sql;
